### ISSUE TITLE
[FEATURE] Adding Commerce Integration

### ISSUE THREAD

**Issue by ArxKnight** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#14]
**Do you own the TS3 Integration application?**
https://invisioncommunity.com/profile/558110-lostking329/

**Is your feature request related to a problem? Please describe.**
Unable to make it so that users who have donated are added to a group like "Donator" or something.

**Describe the solution you'd like**
I would like to see a feature added where if a user donates or buys something from the store that they could receive a tag in the TeamSpeak server to show that they have donated/ bought a specific product.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nathan-fiscaletti** [comment]
The TeamSpeak applications main purpose is to provide linkage between your forum groups and your teamspeak groups. It is not meant to take over as an automation tool on your forums outside of that scope. 

In order to achieve your desired affect, I would recommend setting up [Automation Rules](https://invisioncommunity.com/files/file/7369-automation-rules-full/), if you do not own a copy of this application, you might consider seeing if your commerce application has an option to add someone to a group upon purchase, or perhaps as the option to add them to a specific profile field?

This may still be something I consider adding directly to the TS application in the future, but it's not something close on the horizon.

**Comment by ArxKnight** [comment]
ah ok thanks for the information, I looked into the plugin you mentioned and to do that I need it to its nearly £100 so I think I will leave it for now and look for another way as I cannot see anything about adding them to a group or profile field with the validation of a purchuse in the store settings saldy.
